### ISSUE TITLE
`AssertionError [ERR_ASSERTION]: Invalid callback object specified` when trying to use the deprecated `compile()` API on 0.8.9

### ISSUE THREAD

**Issue by godomainz** [ethereum/solc-js#628] opened 2022-05-22 05:44 UTC
tried all these versions
 `"solc": "0.8.9"`
 `"solc": "0.8.13"`
`"solc": "0.8.14-fixed"`
only thing worked was `"solc": "^0.4.17"`

below is the error I got

```
F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\solc\wrapper.js:97
      assert(typeof callbacks === 'object', 'Invalid callback object specified.');
      ^
AssertionError [ERR_ASSERTION]: Invalid callback object specified.
    at runWithCallbacks (F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\solc\wrapper.js:97:7)
    at compileStandard (F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\solc\wrapper.js:207:14)
    at Object.compileStandardWrapper [as compile] (F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\solc\wrapper.js:214:14)
    at Object.<anonymous> (F:\Blockchain Projects\ethereum-solidity\section_2\inbox\src\compile.ts:7:22)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\ts-node\src\index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\ts-node\src\index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

my package.json
```
{
  "name": "inbox",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "ts-mocha -p tsconfig.json src/**/*.spec.ts",
    "compile": "ts-node src/compile.ts",
    "deploy": "ts-node src/deploy.ts"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@truffle/hdwallet-provider": "^2.0.8",
    "@typechain/truffle-v5": "^8.0.0",
    "@types/expect": "^24.3.0",
    "@types/mocha": "^9.1.1",
    "dotenv": "^16.0.1",
    "ganache": "^7.1.0",
    "ganache-cli": "^6.12.2",
    "mocha": "^10.0.0",
    "solc": "0.8.9",
    "solc-typed-ast": "^10.0.0",
    "truffle": "^5.5.14",
    "ts-mocha": "^10.0.0",
    "ts-node": "^10.7.0",
    "typechain": "^8.0.0",
    "typescript": "^4.6.4",
    "web3": "^1.7.3"
  }
}
```

my Inbox.sol
```
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.9;

contract Inbox {
    string public message;
    
    constructor(string memory initialMessage) public {
        message = initialMessage;
    }
    
    function setMessage(string memory newMessage) public {
        message = newMessage;
    }
}
```
my compile.ts

```
const solc = require('solc');
import { resolve } from 'path';
import { readFileSync } from 'fs';

const inboxPath = resolve(__dirname, 'contracts', 'Inbox.sol');
const source = readFileSync(inboxPath, 'utf8');
const bytecode= solc.compile(source,1).contracts[':Inbox'].bytecode;
const interface_str= solc.compile(source,1).contracts[':Inbox'].interface;
export { bytecode, interface_str };
```

**Comment by matheusaaguiar** [comment] 2022-05-25 22:17
Hi, thanks for the report.
The API has been rewritten since 0.4.x, and the way you are calling `solc.compile` is deprecated.
Please, refer to the current [README](https://github.com/ethereum/solc-js#readme) to understand how it should be invoked now.
Also, solc-js is backwards-compatible with older compilers - i.e. if you use the latest version with the new way of calling it, it will work fine with both 0.4.x and 0.8.x.

**Comment by cameel** [comment] 2022-05-27 14:06
I'm closing this since it works as designed. Please update your code to the current API.

**Closed by cameel** 2022-05-27 14:06 UTC
