### ISSUE TITLE
When I try to import openzeppelin contracts it says " File import callback not supported"

### ISSUE THREAD

**Issue by zhiwenh** [ethereum/solc-js#536] opened 2021-07-11 18:26 UTC
This is the error it gives me when trying to  import an openzeppelin file: Batching.sol:4:1: ParserError: Source "@openzeppelin/contracts-upgradeable/token/ERC20/IERC20Upgradeable.sol" not found: File import callback not supported.

**Comment by cameel** [comment] 2021-07-11 19:15
How are you running the compiler? `solcjs` or `solcjs --standard-json` or from JavaScript?

I'm assuming you have the library installed and want the compiler to load it from disk instead of including it manually in the JSON input? If that's the case and you're using `solcjs` script, remember to specify the `--base-path` option to enable the import callback.

See also a similar issue: #522.

**Comment by zhiwenh** [comment] 2021-07-15 03:15
I'm using the Javascript library. I use 'const output = JSON.parse(solc.compile(JSON.stringify(input)))' to compile the contract.

**Comment by zhiwenh** [comment] 2021-07-15 04:27
Here's my code:

Part of compile script:
`
  const input = {
    language: 'Solidity',
    sources: {},
    settings: {
      outputSelection: {
        '*': {
          '*': ['*']
        }
      }
    }
  };
  contractFiles.forEach(function(contract) {
    if (!contract.endsWith('.sol')) contract += '.sol';
    const contractPath = directoryPath + contract;
    input.sources[contract] = {content: null};
    input.sources[contract].content = fs.readFileSync(contractPath, 'UTF-8');
  });

  const output = JSON.parse(solc.compile(JSON.stringify(input)));

  if (output.errors) {
    console.log(output.errors);
  }
`

Part of smart contract: 
`
// SPDX-License-Identifier: MIT
pragma solidity 0.7.3;

import "@openzeppelin/contracts-upgradeable/token/ERC20/IERC20Upgradeable.sol";
`

And here's the entire error message it outputs:
`
  {
    component: 'general',
    errorCode: '6275',
    formattedMessage: 'Batching.sol:4:1: ParserError: Source "@openzeppelin/contracts-upgradeable/token/ERC20/IERC20Upgradeable.sol" not found: File import callback not supported\n' +
      'import "@openzeppelin/contracts-upgradeable/token/ERC20/IERC20Upgradeable.sol";\n' +
      '^-----------------------------------------------------------------------------^\n',
    message: 'Source "@openzeppelin/contracts-upgradeable/token/ERC20/IERC20Upgradeable.sol" not found: File import callback not supported',
    severity: 'error',
    sourceLocation: { end: 135, file: 'Batching.sol', start: 56 },
    type: 'ParserError'
  },
`

Thanks for the help. I can't seem to import OpenZeppelin files.

**Comment by zhiwenh** [comment] 2021-07-15 11:13
I solved my issue by adding this into the code:

```
  contractFiles.forEach(function(contract) {
    if (!contract.endsWith('.sol')) contract += '.sol';
    const contractPath = directoryPath + contract;
    input.sources[contract] = {content: null};
    input.sources[contract].content = fs.readFileSync(contractPath, 'UTF-8');
  });

  function findImports(_path) {
    if (_path[0] === '.') {
      return {
          contents: fs.readFileSync(path.join(directoryPath, _path)).toString()
      }
    } else {
      return {
          contents: fs.readFileSync(path.join(config.projectRoot, 'node_modules', _path)).toString()
      }
    }
  }

  const output = JSON.parse(solc.compile(JSON.stringify(input), {import: findImports}));

  if (output.errors) {
    console.log(output.errors);
  }
```

**Comment by cameel** [comment] 2021-07-15 18:43
Yeah, that's the recommended way to do it. When you're using solc-js as a library, you basically need to grab all the contracts form disk yourself and include them in the JSON input. Frameworks like Truffle or Hardhat are doing exactly that.

There's also another way that might be simpler for you. You could use an [import callback](https://github.com/ethereum/solc-js#high-level-api). That's what the error message is alluding to - the file could not be found in JSON and you also did not provide any callback so the compiler could not load it. Having a callback might be convenient because the compiler will simply ask you to provide the source whenever it finds an import that's not already in JSON input. For you this means just loading it from disk you have access to it (i.e. your code is not running in a browser).

If you decide to not use the callback, please be careful about absolute paths. You should use only relative ones because you don't want user's local paths ending up in contract metadata (this might affect verification). This topic is now extensively documented so please take a look at the section on [Import Path Resolution](https://docs.soliditylang.org/en/latest/path-resolution.html) in the docs.

I'm going to close this issue since it's not a bug report or a feature request. If you have more questions please drop by at the [#solidity](https://gitter.im/ethereum/solidity) channel on gitter.

**Closed by cameel** 2021-07-15 18:43 UTC

**Comment by hammersharkfish** [comment] 2024-01-22 04:48
Any improvement on this ? 
Can solcjs handle imports on it's own ?
