### ISSUE TITLE
I can't load solc: TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by SunkieChai** [ethereum/solc-js#525] opened 2021-06-07 03:35 UTC
when  my webpage load, the browser console show me like this:

Uncaught TypeError: Cannot read property 'match' of undefined
    at patch (polyfills.js?a0a3:35)
    at patch (graceful-fs.js?0da7:104)
    at Object.eval (graceful-fs.js?0da7:96)
    at eval (graceful-fs.js:375)
    at Object../node_modules/graceful-fs/graceful-fs.js (chunk-vendors.js:6792)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at Object.eval (index.internals.js?898b:9)
    at eval (index.internals.js:124)
    at Object../node_modules/gulp-sourcemaps/src/init/index.internals.js (chunk-vendors.js:6849)
    
How to fix it?

**Comment by cameel** [comment] 2021-06-07 09:27
Can you post the input you're giving to the compiler? Preferably a minimal example that causes this crash.

**Comment by cameel** [comment] 2021-08-08 18:55
Closing since I don't think this is caused by a bug in solc-js. The stack trace does not refer to any files from the project and there are not enough details to even try to reproduce this.

Feel free to reopen with more details about the problem if you think this is actually something in solc-js.

**Closed by cameel** 2021-08-08 18:55 UTC
