### ISSUE TITLE
`npm install` fails

### ISSUE THREAD

**Issue by vrde** [ethereum/solc-js#475] opened 2020-06-26 08:27 UTC
Hi, I'm running on node `v12.18.0` and when I run `npm install` I get this error:

```
➜  solc-js git:(master) npm i
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> solc@0.6.10 prepublish /tmp/solc-js
> node downloadCurrentVersion.js && node verifyVersion.js

Downloading correct solidity binary...
Retrieving available version list...
Downloading version soljson-v0.6.10+commit.00c0fcaf.js
Hash mismatch: 0x620163da7ee7b2622c9ee48b06110a52739f633189555148a3b5ecf767e60cfb vs 0x3c6ebdcd656156ea3488ae96fb42dac57e0f8bb67d08e3008cf01d8da8f4cdef
```

**Comment by hrkrshnn** [comment] 2020-06-26 08:44
Possible duplicate of: https://github.com/ethereum/solidity/issues/9261

**Comment by chriseth** [comment] 2020-06-29 15:12
Indeed, should be fixed.

**Closed by chriseth** 2020-06-29 15:12 UTC
