### ISSUE TITLE
Error when loading solc-js in a browser: `TypeError: Cannot use 'in' operator to search for '_solidity_version' in undefined`

### ISSUE THREAD

**Issue by HsienW** [ethereum/solc-js#617] opened 2022-04-10 11:23 UTC
Hi

I use it in a browser environment, it will give an error

regardless of using load solc into the global variable window.Module
Or import in ES6 syntax

both "TypeError: Cannot use 'in' operator to search for '_solidity_version' in undefined"

I just simply imported, without writing any code, it went wrong

![image](https://user-images.githubusercontent.com/20525933/162615495-48a9df0d-3b07-42da-9698-5c91438d9a85.png)

This confuses me, seems to be an issue from the package itself

**Comment by cameel** [comment] 2022-04-14 12:33
Can you provide more details about your environment? OS, browser and version, solc-js version, compiler binary version, etc.

Did you load the compiler binary with a `<script>` tag as shown under [Browser Usage in the README](https://github.com/ethereum/solc-js#browser-usage)?

**Comment by cameel** [comment] 2022-05-27 22:55
I'm closing this since there's not enough detail provided to reproduce the problem and I think it's just incorrect usage. Feel free to reopen and provide more information if you think this is actually a bug in solc-js.

**Closed by cameel** 2022-05-27 22:55 UTC
