### ISSUE TITLE
Solc-js Causes Node Scripts to Delay Finishing

### ISSUE THREAD

**Issue by chase-manning** [ethereum/solc-js#654] opened 2022-09-07 17:39 UTC
If `solc` is imported into any node script, it causes that script to delay for a few seconds after finishing.

I have created a small repository to replicate this issue:

https://github.com/chase-manning/solc-bug-reproduce

Details on how to replicate are in the readme for that repo.

But in short, this script:
```
const solc = require("solc");
console.log("Script finished running");
```
when run with, for example, `node index.js` will lag for about 5 seconds after `Script finished running` is logged.

But this script:
```
console.log("Script finished running");
```
Will stop running immediately after the line is logged.

This issue cannot be replicated by importing any other package, and happens just with `solc`.

**Comment by cameel** [comment] 2022-09-07 18:05
Yes, it's a known issue and it seems to actually be a problem in node.js: https://github.com/nodejs/node/issues/36616

Thanks for the report but I'm going to close this since the problem is already tracked in https://github.com/ethereum/solidity/issues/9297.

**Closed by cameel** 2022-09-07 18:05 UTC

**Comment by chase-manning** [comment] 2022-09-07 18:10
@cameel Thanks! Do you know of any workarounds that I could use? 😄

**Comment by cameel** [comment] 2022-09-07 18:12
On older node.js versions a manual `process.exit()` used to help. That stopped working on node.js 17 but `node --wasm-dynamic-tiering` should work. Not sure if that feature was already released is a stable node.js version though.
