### ISSUE TITLE
unexpected result using --base-path

### ISSUE THREAD

**Issue by LndnMdiaLb** [ethereum/solc-js#641] opened 2022-07-08 10:58 UTC
i am unclear on what 'root of source tree' means when using the `base-path` flag

`$(npm bin)/solcjs --bin --output-dir build --base-path ./contracts Test.sol`
returns : `Error reading Test.sol: Error: ENOENT: no such file or directory, open 'Test.sol' `

`$(npm bin)/solcjs --bin --output-dir build --base-path . contracts/Test.sol`  works and compiles contract

**Comment by r0qs** [comment] 2022-09-08 10:30
Hi @LndnMdiaLb, it is the root path of your project source tree. If you omit it, the base-path is considered to be the current working directory. So you could just use:

```
solcjs --bin --output-dir build contracts/Test.sol
```
If you want to use `contracts` as the base-path, you need to do:
```
solc.js --bin --output-dir build --base-path ./contracts contracts/Test.sol
```

Please consider this [note](https://github.com/ethereum/solc-js#usage-on-the-command-line) when changing the base-path:
```
Note: ensure that all the files you specify on the command line are located inside the base path or one of the include paths. The compiler refers to files from outside of these directories using absolute paths. Having absolute paths in contract metadata will result in your bytecode being reproducible only when it's placed in these exact absolute locations.
```

**Comment by cameel** [comment] 2022-09-09 19:49
You can find detailed docs about how path resolution works in [Import Path Resolution](https://docs.soliditylang.org/en/latest/path-resolution.html).

In short, the main purpose of base path is to be the location that direct imports are resolved against. I.e. if the base path is `/some/path/`, and you have `import "a/b/c.sol"` in your contract, the compiler will look for the file in `/some/path/a/b/c.sol` on disk.

Base path is **not** the same thing as your working directory even though by default they have the same value. When they're different, on the command-line it's the working directory that counts:
```bash
cd /some/other/path
solc --base-path /some/path/ a/b/c.sol
```
In the above `a/b/c.sol` refers to `/some/other/path/a/b/c.sol` because that's how everyone expects relative paths to work on the CLI. It does not magically become `/some/path/a/b/c.sol`

**Comment by cameel** [comment] 2022-09-09 19:49
In any case, closing since this is not a bug.

**Closed by cameel** 2022-09-09 19:49 UTC

**Comment by r0qs** [comment] 2022-09-10 12:00
> Base path is **not** the same thing as your working directory even though by default they have the same value. When they're different, on the command-line it's the working directory that counts

Maybe it would be nice to add this comment in the readme as well?

**Comment by cameel** [comment] 2022-09-10 13:17
Why not. Feel free to submit a PR to adjust that. We could add a sentence or two on that and maybe link to specific bits in the import path resolution docs. Like, the `--base-path` option could be a link to the section on base path and we could also link to https://docs.soliditylang.org/en/latest/path-resolution.html#cli-path-normalization-and-stripping.
