### ISSUE TITLE
Can't run  command :  "yarn solcjs --bin --abi --include-path node_modules/ --base-path . -o . SimpleStorage.sol".

### ISSUE THREAD

**Issue by apuser333** [ethereum/solc-js#653] opened 2022-08-28 05:37 UTC
When I run "yarn solcjs --bin --abi --include-path node_modules/ --base-path . -o . SimpleStorage.sol". It dislays an error

Error: Error reading SimpleStorage.sol: Error: ENOENT: no such file or directory, open 'SimpleStorage.sol'
error Command failed with exit code 1.

Can someone pls help?

**Comment by r0qs** [comment] 2022-09-08 12:10
Hi @apuser333 please see the instructions on how to install and run solc-js [here](https://github.com/ethereum/solc-js#nodejs-usage).

If you want to build from source, you can do de following after clone this repo:
```
npm install
npm run build
./dist/solc.js --help
```

**Comment by cameel** [comment] 2022-09-09 16:18
I cannot reproduce this. This runs just fine for me:

```bash
yarn add solc
echo "contract SimpleStorage {}" > SimpleStorage.sol
yarn solcjs --bin --abi --include-path node_modules/ --base-path . -o . SimpleStorage.sol
```

Does the file exist? How are you installing `solc`? What platform are you on?

In any case, this looks more like a usage problem than a genuine bug in the compiler so I'm going to close it. Feel free to reopen if you can show how it can be reproduced. If you're just looking for help in using the compiler, the [#solidity](https://gitter.im/ethereum/solidity) channel is a better place ask questions.

**Closed by cameel** 2022-09-09 16:18 UTC
