### ISSUE TITLE
Jest - "TypeError: soljson.cwrap is not a function"

### ISSUE THREAD

**Issue by cofdev0** [ethereum/solc-js#130] opened 2017-07-27 10:57 UTC
I try to use solc in a Jest test suite here
https://github.com/cofdev0/bean-counter/blob/master/src/token.spec.ts#L22
Is there a way to use solc in Jest tests or is it like with Browserify 'very likely not possible'?

the console output:
yarn test v0.27.5
$ tsc ; jest --coverage
 FAIL  dist/token.spec.js
  ● Token › encountered a declaration exception

    TypeError: soljson.cwrap is not a function
      
      at setupMethods (node_modules/solc/wrapper.js:7:29)
      at Object.<anonymous> (node_modules/solc/index.js:3:18)
      at Suite.<anonymous> (dist/token.spec.js:15:16)
      at Object.<anonymous> (dist/token.spec.js:14:1)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  Token
    ✕ encountered a declaration exception (2ms)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total

**Comment by axic** [comment] 2017-08-01 01:50
Duplicate of #125.

**Closed by axic** 2017-08-01 01:50 UTC
